
import React, { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { toast } from "@/components/ui/use-toast";

const Distill = () => {
  const { url } = useParams<{ url: string }>();
  const navigate = useNavigate();
  const [isLoading, setIsLoading] = useState(true);
  const [originalContent, setOriginalContent] = useState('');
  const [summary, setSummary] = useState('');
  const [error, setError] = useState('');

  useEffect(() => {
    if (!url) {
      setError('No URL provided');
      setIsLoading(false);
      return;
    }

    const fetchAndDistill = async () => {
      try {
        // Step 1: Decode and format the URL
        let targetUrl = decodeURIComponent(url);
        if (!targetUrl.startsWith('http')) {
          targetUrl = `http://${targetUrl}`;
        }

        // Step 2: Fetch content using r.jina.com
        const jinaUrl = `https://r.jina.ai/${targetUrl}`;
        console.log('Fetching content from:', jinaUrl);
        
        const contentResponse = await fetch(jinaUrl);
        if (!contentResponse.ok) {
          throw new Error(`Failed to fetch content: ${contentResponse.statusText}`);
        }
        
        const contentText = await contentResponse.text();
        setOriginalContent(contentText);
        
        // Step 3: For now, we'll use a placeholder for the OpenRouter integration
        // In a real implementation, you would send this to OpenRouter for summarization
        setSummary('This is a placeholder summary. In the actual implementation, this would be generated by OpenRouter API using the extracted content.');
        
        setIsLoading(false);
      } catch (err) {
        console.error('Error:', err);
        setError('Failed to process the URL. Please check the URL and try again.');
        setIsLoading(false);
        toast({
          title: "Error",
          description: `Failed to process the URL: ${err instanceof Error ? err.message : 'Unknown error'}`,
          variant: "destructive"
        });
      }
    };

    fetchAndDistill();
  }, [url]);

  const handleBack = () => {
    navigate('/');
  };

  if (isLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-center">
          <h2 className="text-2xl font-bold mb-4">Processing...</h2>
          <p className="text-gray-600">Extracting and summarizing content from {decodeURIComponent(url || '')}</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <Card className="w-full max-w-2xl shadow-lg">
          <CardHeader>
            <CardTitle className="text-2xl font-bold text-red-600">Error</CardTitle>
          </CardHeader>
          <CardContent>
            <p>{error}</p>
          </CardContent>
          <CardFooter>
            <Button onClick={handleBack}>Back to Home</Button>
          </CardFooter>
        </Card>
      </div>
    );
  }

  return (
    <div className="min-h-screen p-4 bg-gray-50">
      <div className="max-w-4xl mx-auto">
        <Button onClick={handleBack} variant="outline" className="mb-4">
          ← Back to Home
        </Button>
        
        <Card className="mb-6 shadow-md">
          <CardHeader>
            <CardTitle>Summary</CardTitle>
            <CardDescription>
              Distilled content from: {decodeURIComponent(url || '')}
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="prose max-w-none">
              {summary}
            </div>
          </CardContent>
        </Card>
        
        <Card className="shadow-md">
          <CardHeader>
            <CardTitle>Original Content</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="prose max-w-none overflow-auto max-h-[500px]">
              <pre className="whitespace-pre-wrap">{originalContent}</pre>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
};

export default Distill;
