// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mibqumffyhfbuddsyuaq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1pYnF1bWZmeWhmYnVkZHN5dWFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMTcwNjksImV4cCI6MjA1Nzg5MzA2OX0.yLoxY7fr_4yuS-l8Wmt6YlH1S-DBXNLhxRJrO4M-Htc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);