
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mibqumffyhfbuddsyuaq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1pYnF1bWZmeWhmYnVkZHN5dWFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMTcwNjksImV4cCI6MjA1Nzg5MzA2OX0.yLoxY7fr_4yuS-l8Wmt6YlH1S-DBXNLhxRJrO4M-Htc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Add error logging for debugging Supabase connection issues
supabase.auth.onAuthStateChange((event, session) => {
  console.log('Supabase auth event:', event);
  if (event === 'SIGNED_OUT') {
    console.log('User signed out');
  } else if (event === 'SIGNED_IN') {
    console.log('User signed in:', session?.user.id);
  } else if (event === 'TOKEN_REFRESHED') {
    console.log('Token refreshed');
  } else if (event === 'USER_UPDATED') {
    console.log('User updated');
  }
});

// Add a function to test Supabase connectivity
export const testSupabaseConnection = async () => {
  try {
    // Instead of querying a table that might not exist, let's check if we can connect to Supabase at all
    const { data, error } = await supabase.auth.getSession();
    
    if (error) {
      console.error('Supabase connectivity test failed:', error);
      return { success: false, error: error.message };
    }
    
    // Try invoking a function to verify edge function connectivity
    try {
      await supabase.functions.invoke('process-url', {
        method: 'HEAD',
        body: {}
      });
      console.log('Edge function connectivity test successful');
    } catch (funcError) {
      console.log('Edge function test failed, but base connectivity succeeded:', funcError);
      // We'll still consider this a success since the base connection works
    }
    
    console.log('Supabase connectivity test successful');
    return { success: true };
  } catch (err) {
    console.error('Supabase connectivity test threw an exception:', err);
    return { success: false, error: err instanceof Error ? err.message : String(err) };
  }
};
